#include<bits/stdc++.h>
using namespace std;
#define ll long long
#define fo(i, a, b) for(int i = (a), _b = (b); i <= _b; ++i)
#define rep(i, a, b) for(int i = (a), _b = (b); i >= _b; --i)
#define ngtphuoc30 ios_base::sync_with_stdio(0);\
    cin.tie(0);\
    cout.tie(0);

const ll mod = 1e9+7, mn = 1e5+5, phi = mod-1;
ll m, a[mn], p[mn], cnt = 1, sum = 1, prod = 1;
ll binpow(ll k, ll e, ll _mod){
    ll ans = 1;
    while(e){
        if(e&1) ans = ans*k%_mod;
        k = k*k%_mod;
        e >>= 1;
    }
    return ans;
}
ll inv(ll _a, ll n){
   //1+a+a^2 = a^(n+1)
   //         /a-1 
   ll fi = (binpow(_a, n+1, mod)-1)%mod;
   if(fi < 0) fi += mod;
   ll se = binpow(_a-1, mod-2, mod);
   return fi*se%mod;
}
ll exp(ll _a, ll e){
    //n = n* 2^x
    //s = (a[1]+1)*(a[2]+1)*...*(a[m]+1) % 1e
    //a^(n*s)
    //a^(n*s % phi )
    return binpow(_a, e, mod);
}
ll pr[mn], s[mn];
int main(){
    ngtphuoc30
    //freopen(".inp", "r", stdin);
    //freopen(".out", "w", stdout);

    //1 + a + b + ab = (a+1)(b+1)
    //1 + a + aa + ab + aab + b = (a^2 + a + 1)(b+1)

    //1 * a * b * ab 
    //1 * a * aa * ab * aab * b
    //* (a[i]+1)
    cin>>m;
    s[m+1] = 1;
    pr[0] = 1;

    fo(i, 1, m){
        cin>>p[i]>>a[i];
        cnt = cnt*(a[i]+1)%mod;
        sum = sum*(inv(p[i], a[i]))%mod;
        pr[i] = pr[i-1]*(a[i]+1)%phi;
    }
    rep(i, m, 1) s[i] = s[i+1]*(a[i]+1)%phi;
    fo(i, 1, m){
        ll e = a[i]*(a[i]+1)/2%phi;
        //tich/(a[i]+1)
        ll tich = pr[i-1]*s[i+1]%phi;
        e = e*tich%phi;
        prod = prod*exp(p[i], e)%mod;
    }
    cout<<cnt<<' '<<sum<<' '<<prod; 
}










/*
KKKKKKKKKKKKXXXXXXXXXXXXKKKXXXXXKKKKKKKKKKKKKKKKK00000000OOkkkOOkxoc:ldkOK0koc:;''l0XXXXXXNNNNNXXXNNX0Okoc,'.........''''',;:ccldxkOOO0Oxl:cx0XNNXXXNNXXOdclx000Okxdol:;,,'''............',:cox0XNNNNNNXXNNXXXOo;'....'',,:cdxkxlclxkOOOOO00000000000OOOOOOO0000OOOOkkkkxxxxdoolllllllcccccccccccccccllllccc
KKKKKKKKKKKKKXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKK0000000000000Okkkkkdl:cdO000ko,':lc:cd0XXNNXXXNNNNXXX0kdl:,'''',,,,,',,;:clodxkkOOOOOOOOOO00kdlloxO0KKK0OkxoodkO0000000OOOkkxdoolc:;,,,,,,,'''''.;xKXXNNNNNNNNNXXKOOkdl;'......';lxxdlcldkOO0000OO00OOOOOkkkkOOOOOkkkkxxddoollllccccccccccccccccccccccccccccccc
KKKKKKKKKKKKKXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKK0000000KKK00OOOOxoccldO0Okdc,..,oO0KKXXXNNXXXXXXXXXNKdccllloodddddxxxxkkkkOOOOOOO0OOO00000000OkxolloxxdooooxkOO00000000000000OOOOOOOkkkxxxxxxxxoco0NNNNNNNNNXNNNNNXXXXXKkl;'..''..':lddlcoxkO0000OOkkkkxxddddddddddooooolllcccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKKXXXXXXKKKKKKKKKK0000000000000000000KKKKKKK00OOkdc:lxkkoc;,...,lkKXXXXXNNNXXXXXNNXXNNXOxdxO00000OO000000000000000000000000OOOO0000OkkkkOOOOOOO0000000000000000OO00000000000000OkdloONNNNNNXXXXXXKKKXXNNNNNKko,..'''..';lddoloxO00Okxdoooolllllllllllcccccccccccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKKXXXKKKKKKKKKKKK00000000000000000000KK0000000Oxlccoddl;.....,lOKNNNXXNNNNNNNNNNNNNNNXXKOxdO0000000000000000000OOOOO000OOOO00OOOO000OOO0000000O0000000000000000000000OOO000000OOOxc:xKXNNNNNXNXKxl:lxOKXNNNNX0l'..''''..';oxdoloxkxdolccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKXXXXKKKKKKKKKK000000000000000000000000OOO00Oxoclddo;......,cxKXXXXXXXKOdodOXNNNNNNNXXKkddxO00O0000000000000OOOOOOOOOO00OO00000O00000OOO000000000000000000000000000000000000O0OO0Odc:cdOKXXXXX0xl;..,:cdOKXXXKd,..''......';lddllcllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKXXXXKKKKKKK00000000000000000000000000OO00Okdccldo;.......'lOKXNNXKKOd:,'.';lxOKKKXX0koclxO000O000000OOOOO000000000OOO000000000000000000000000K00O00000000000000000000OOO000000OO00koc::coddoc:cooc,...',;:loo:'.....,:::,..';ldoc:::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKKKKKKKKKKKK000000000000000000000000OOOO0ko::oxdc'..'''...'ck0KKOkxl;'..,cooooooddxddoodkO000OOO0OOOOOOOOO00000000000OOOO0000OOO0000OOO00OOO0000OO0000000000000000OOOOOOOOOOOO000O000kxdddddoodxO0ko:'...........'...:k00Okd:,';odlc::ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKKKKKKKKKKKK0000000000000OO000000000OOOkdc;:odl,...'''.....',:c:;,''..':okO0OOOkkOOOOOOOO000OOOOOOOOOOOOOOOO00000000OOOOO0000OOOOOOOOOOOOOOOO000000000000000000000000OOOOOOOO000000000OOOOOO0OOO000kdc;'......'''''..:OXNNNX0xl;;cdd:;::ccccccccclllllllllccccccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKKKKKKKKKK0000000000000K00000000K0OO0KOl;;ldd;...,;;,''''......''...';lkO0000000000000000000000000000OOOOOOOO00000000000000000000000OOOOOOOOOO00000000000000000000000000000000000000000000000000OO00Okdl;'....'''....;xKNXXXXXKkl:codl::cc:::::cccllccllccccccccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKKKKKKKKKK0000000000000000K0Okdooooodoc;cdxl,.':okOkd:'..''.''.....,:dO00000000000000000000OO00000000OOOOOOOOOOOOOOO00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000OOO000000000000O00000OOO00000OOOOOkxo:,.........':xKXXXXNNXKkccol:;;clc::cccccllcccccccccccccccccccccccccccccccccccccccccccc
KKKKKKKKKKKKKKKKKKKKKKKK000KKK0000000Odolc;:oddl;';oxo;,cxKXNNKd:'..''''...';cdkO00O000O0OO00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000OOOO000OOOOOOOkdl;''.......,oOXXXNNNXXOo;,:lxOkodO0koc:cclllccccccccccclllccccccccccccccccccccccccccc
KKKKKKKKKKKKKKKKKKKKKKKKK00KKK000000koclkxod0XXKOdc;',ckKNNNNXOc'.'''.....:oxOO0K00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdc;'......':d0XXXNNXOl;lkKNXkllxdl:;;:lllllllllllllllllllllllllllcccccccccccccccccc
KKKKKKKKKKXXXXXXXKKKKKKKKKK00000000Oo::lddox0XNNXXOdox0XNNNNNOl,..'...',cokOO0O0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000OOOOO00OkkOO0Okdl:;'....,cxKXXKxc:d0XXXNKOkkxdl:;cllllllllllllllllllllllllllllccccccccccccccccc
KKKKKKKKKXXXXXXXXXXKKKKKKKKKKKKKK000dcdO000KXXXNNXXXXXNNNNXXOc'...'';cdkOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOO0Oxoodk00OOkkxoc;,''.;d0XKOxkKXNNXNNXXK0xc;cloollllllllllllllllllllllllllccccccccccccccccc
KKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKK0K0xldOKNXXNXXXXXXXNNXXXXX0d;...,coxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOko::okOOOOOOOOkdo:,cxKNNXXXXNNNNNNXKOo;,:ldooooooolllllllllllllllllllllccccccccccccccccc
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOxccx0XXXXNNNXXNWNNXXXNXKOd:,:dOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdc;cdkO0OOO00kl:oOXNNNNXXXXXNNKko:;::;;ldoooooolclllllllllllllllllcccccccccccccccccccc
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKXX0dc;cx0XNNXXXNNNNNNNNNNNNX0xcok00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0Odc,;oO00000Od:ckXNNNNNNXXXNNKxl;''cdoc:cooooollccllllllllllllllllllccccccllllllllllll
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKOdc;;cox0XXXXNXXXXNNXNNNXXX0doxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkl;:ok000Okdlo0NNXXXNNXXNNXKKK0xocldo:;clollllllllllllllllllllllllllllllllllllllllll
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXKKKklcldkkl:dKNNNXXXXXNXXNNNNNXkclkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkd:;okOO0OdclOXNXXNNNNNNNXXXNNNXklcclc;coolllllllllllllllllllllllllllllllllllllllll
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXK0kl:lxkxdloOXNXXXNNXNNXXXNNX0dccokOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkoc:lkO0Odc:okKXXXKOkxk0XNNNNNNKx;;ll::cllllllllllllllllllllllllllllllllllllllllll
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKd::okOxlcd0XNNNXXNXXXNNXXXKxlloxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0Odc:okO0Oxocloddollll:cxKNNNNNX0o:cll:;:llolollllllllllllllllllllllllllllllllllll
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKX0xlcdOOxccx0XXXNNX0kkkOO0OkdoloxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOkkkxxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdc;cxO0OOkxxddxxkkkdlcoOXNXXXKkocodc,;coollllllllllllllllllllllllllllllllllllll
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOdclxOOxlcxKNNXXX0xlccloooooooxO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOxc:okOOOOOOOOOOOOOOOOOOOOOO00OOOOOdc::dOOO00OkkOOOOOOxl:cdkOxoc;;cdkdc;;clllllllllclllllllllllllllllllllllllllll
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOl:ldOOxccd0XNXXXKxccdkOOOOOOkkOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOO0ko:;cxOkO0OOOOOOOOOOOOOOOOOOOOOO00kxc,:dk000OOOOkkOOOOkdlcc:,...'cxOOd:,:clollllllllllllllllllllllllllllllllllll
00KKKKKKKKKKKKKKKKKKKKKKKKKKKOd::dOOxo:cOXXNNX0oclxO00OOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkOOOOOOOOOOOOOOOOOOOOOOd:;cxOOOOOOOOOOOOOOOOOOOOOkOOOOOOOxc;:dO0OOOOOOkkOOkOOkxdc,...'cx00ko:,:lolloollllllllllllllllllllllllllloolll
000KKKKKKKKKKKKKKKKKKKKKKKKK0dccdkOOxl;:kXNXKxl:lxOOO0OOOOOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxdddkOOOOOOOOOOOOOOOOOOOkxl;:dkOOOOOOOOOOOOOOOOOOkkOOOOOOOOxc;cokOOOOOOOOOOkkO00Od:'..',lkOOxl,;coooooooooooooooooooollllllllloooooooo
000KKKKKKKKKKKKKKKKKKKKKKKK0kl:okO0Oko,'lkOxl:cdkOOkOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkOOOOkkxl;:dOOkOOOOOOOOOOOOOOOOOkxl;;lkOOOOOOOOOOOOOOOOkkOOOOOOOOOkdc;:dOOOOOOOOOOOkkxdl:;;;:;,:oxkkd:;cldddddddddddddddddddoollllllloooodddd
0000KKKKKKKKKKKKKKKKKKXKKXKOoclxOOOOOx:.',,''cxOOOOOkOOOOOOOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkOOOkOkdc:dOOOOOOOOOOOOOOOkOOOOOOko:;lxOOOOOOOOOOOOOkxddxkOOOOOOOOkdc:lxOOOOOOOOOOxl;;:clooolc:cdOkxo:;coxxxxxxxxxxxxxdddddoollllllooodddddx
000000KKKKKKKKKKKKKKKXXXXK0xccdkOOOOOx:''',,:dOOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkOOOkOkxdlcokOOOOOOOOOOOOOOOOOOkOOkd:;cdkOOOOOOOOOkdc;,;cdkOOOOOOOOkdc:lkOOO0OOOkd:,;cooooodoc;:okOOko;:ldxxxxxxxxxdddddddollllllllooodddddd
0000KKKKKKKKKKXXKXXXKXXXX0klcokOOOOOkdc,,,;:lxOOOOOkkkOOOOOOOOkkkkkkOOOOOOOOOOOOOOOOOOOOkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkOkkkkkkkkOOkkkkxl,;okOOOOOOOOOkkkkOOOOkkOOkxl::oxkOOOOOOko;;;',lxOOkOOOOOOkkd::oxO0OOkko:;:clc:::clol;;okO0Oxl;;lddddddxxxdddoooolllloooooooddddooo
KKKKKKKKKKKKKKXXXXXXKKKXXOl:lxkOOOOOdl:;,,,cokOOOOOkkkOOOOOOOOkkkkkkOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkOkkkkkkOko'.:dkOOOkOOOOOOOOOOOOkkkkOOko:;cxOOOOkdc;,,;;lxOOkkOkOOOOOOko:;lOOOkko:,:cc:cllc;;cc;;okOOOkd;':oodddddddddddooollloodddddddddoooo
KKKKKKKKKXXXXKKKXXXXKKXXKx::dkOOkkOkdc;,;,,cxOOOOOOOkkkkkkkkkkkkkkkkkkOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkOOd:,:ldkOOOOOkOOOOOkkkkkkkkkkOxo:;cdOOko:,,,';okOOkOOOkkkOO000kl,:dkOOdc;;:c:cdkkxc''::;okkkkkxc,:looddddddxxxdddoooooddddddoooooooo
KKXXXXXKKXXXXKKKXXXKKXXKklcokOOOkkOkd:'';;;lkOOOOkOOkkkkkkkkkkkkkkkkkkOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOxc:occdOOOOOOkOOkkkkkkkOOOkkOOkxc,:olc:::,,:ok0OOOOOOOOkO0KKK0xc;;okkdc,,cc:cxOOkl'.;;;lxkkOOkdc;:lddoooddddxddddooddddddddoooooddd
XXXXXXXKKXXXKKKKKXXKXKKOocoxkOOOOOOko:'',;cokOOkkkkOkkkkkkkkkkkkkkkkkkkOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOd;cxdllxkOOOOkkOOOOOkkkkOOOOOOOOdc,..,;,';lxkOkkOOOkkOOOO0KKKKOx:,:dkxl;,cc;;okOOd;',,,lkOOkkkxc''cdddddddddddddddddxxxxxxddoooodxx
XXXXXXKXKKKKKKXKKKKXXKOoccdO0KK0OOOOxdl:,,ldkOOkkkkOOkkkkkkkkkkkkkkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOko;cOKklcdOOOOOOOOkkOOkkkOkkkkkOkdc,',;,';lkkOOOOOOOOkkkOO00KKK0ko:;cxkd:,:c;,:dO0kc;;,,oO0Okdl:;,,;lxkkkxxddooooddxxxkkOkkxxdoooddx
XXXXXXXXKKKKKKKKK0000ko:;lxOKXXK0OOOOkxl,,lxkOOkkkkkkkOOOOkkkkkkkkkkxdkOOOkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkkkkkkkOOOOOo;cOXKxccokOOOOOOkkOOkOOOkkkOOkxc,;:;,;cdkOkkkOOOOOkkkkkkOKKKK0Okd:;okxo:;:c;,cxOkd:;',okkdc:clloc;:okOOkkxdooooodxkkkkkOkkkxxddddd
XXXXKKKK000000OOkxdddl;,;lk0KXXK0OOOOOkl,,okkkkkkkkkkkOOOOkkkkkkkkkxooxkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOd:ckXXKx:ckOO00OOOOkkOkkkkkkkdl;;:c;..,loddoodddoooollccldOKKK000koccokkl;,::,;okOxc'.':lc::lllodoc:cdOOOkxdolllodxxxxxxkkkkkkkxxxx
XKKK0Okkxxddddoolcccc:,':dk0KXKK0OOOOkxl,;dkkkkkkkkkkkOOOkkkkkkkkkkdccdkOOkkkkkkkkkkkkkkOOOOkkkkkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkOko:lOXXX0dlodkkkkkxdoooooollc:;;;cl:'...',,,,;:::;;;:c:;,'cxO00OOOOxl;cxOxc;,;;;cdOOd,...';ccc:::lolc:oO0Okxoooloddxxdddddxxxkkkxxxd
OOkxxdollcc::c:::::::;,;okO0KKK00OOOOkdl;cxkkOkkkkkkkkkOkkkkkkkkkkko::dkOOkkkkkkkkkkkkkOOOOkkkOOOkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOkkkkkkkkkkOOOO0OOkkOOOd:lOKXXXKx:;:ccc::;,,'',,,,,;:lodoc:;,,,,,;;:::::::::::cldkOOOOOOkxl,,lxkxc'';,,lO0d,...';;;coc::cl:;lkOkxdooooooddddoooodddddddooo
olllccc:::::::::::::;,,cdOOO0000OOOOOkdc:lxOkkkkkkkkkkkkkkkkkkkkOOko;;dkOOOOOkkkkkkkkkOOOkkkkkOOkkkOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkkkkkkkOOOOOOOOOOOOOO00KK0OkkOOOd:lOXXXXXKx:'',,;;;,,;;;;::;;:llc:::;,,..':clodddxxxkkkkOOOOOkkkkxl;,';cll;..'..,lol,...,:ldkko::cc:,:dxddoooooloooooooooodoooooooo
:::::::::::::::::::;,.,lxOOOOOOOOOOOOxoccokOOkkkkOOOOkkkkkkkkkkkkkko;;okOOOOOkkkkkkkkkOOOkkkkkkxdoxOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkkkkkkkOOOOOOOOOOOOO0KXXKOkkOOOd:lOXXXXXNKx:,,:loooodoodxd:,,;;;:lodddc,;dkkOOOOOOOOOkkkOOOOOOkxo:;colc:::;;,'...','..,cxOOOko::cc:,;loddddddooollllloooddddoooooo
:::::::::::::;;;:::;'.,lxkkkkkkkkkOOOxocldkOOkkkkOOOkkkkkkOOOkkkkkxo::dkOOOOOkkkkkkkkkkkkkkkkkxoccdOOOOOkkkkkkkkkkkkkkkkkkkkkkkkOOOkkkkOOOkkkkkkkkOOOOOOO00OOO0KXXKOkkkOkdclkKXXXNNXXOc:okOOOOOOOko:;,,,,cxOkkkkdlcoxOOOOOkkkOOOkkkOOOOOOko:;ldlc:ccc:::;'.',,'';lkOOOko::cl:',cooddddoooollllloodddddddoooo
:::ccccc::::;;;;;::;..;okkkkkkkkkkkkkxlclxkkOOkkkkOOkkkkkOOOkkkkkkxo::dkOOkkkkkkkkkkkkOOkkkkOkdl:cdOOOOkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOkkkkkkkOOOOOOOO000OOOKXXK0kkkOkdclkKXNXXXXXXOo:lxOOOOOko:,,;,:oxkOOOkkkxl:okOOOOkkOOOkkkOkkkOOOko:;cl:;coddddddl:,',,',cdxxxdc;:ll:'':odddoolllllllllloooddxxxxxxx
:ccccccc:::;;;;;;:;,..;dkkkkkkkkkkkkkxlcoxkkOOkkkkkkkkkkOOOOkkkkkkxo::dOOkkkkkkkkkkkkkkkkkkkOkdl:lxOOOkkkkkOOkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkkkkkkOOOOkkOO00KK0O0KXXK0OOOOkdclx0XNXXXNXNXOl:ldkOOxl;;:;,:oxkkkkOOOkxl;cdkOOOOOOkkkkOOOkkkOOkd:;lc;:lxOOOOkkko;,,,'.'',,,,',coo;.'cdxxddddolllllllllloodxkkkkkk
ccccccccc::;;;;;::;,..:dkkOkkkkkkkkkkxl:oxkkOOkkkkkkkkkkkkkkkkkkkkxo::dOOOkkOOkkkkkkkkkkkkkkOkdl:lxOOOkkkkkOOkkkkkkkkkkkkkkkkkkxddxkOOOkkkkOkkkkOOOkkkOOO0000O0KXXK0OOOOOdclxKNNNNNNNNXKOo:cxkxc;;;;;:dkkkkkkOOOkxoc:cxOOOOkkOOOOkOOOkkkkkxc:lc;;lxOOkkkOOd:,,'..,;:::cclool,.'lxkkkkOkkxdollllcccloodxxxxxx
ccccccccc:::;;;;::;'.'cxkkOkkkkkkkkkkxc:lxkkOkkkkkkkkkkkkkkkkkkkkkxo::dOOOkOOOOkkkkkkkkkkkkkOkdl:lxOOOkkkkOOOOkkkkkkkkkOOkkOOkkxolxOOOkkkkkOOkkOOOOkkkOOOO0OOOO0KK0OOOOOOdccxKNNXXNXNNXXX0dlc::;;:;,cdkOOOkkkkkkkkkd::okOOOOOOOOOkkOOOkkkkxoc:::;:dOOkkkOkd;......';:;;;::c:;;:lxO00OOOOOkxoollllllloooooooo
lllllllcc:::;;;;::,'',lxkOOkkkkkkkkkkxc;lxkkkkkkkkkkkkkkkkkkkkkkkkxo::dOOOOOOOOOkkkkkkkkkkkkOkdl:lxOOOkkkkOOOOkkkkkkkkkOOkkkOkxdllxOOOkkkkkOOkOOOOkkkOOOOOOOOkOO00OOOOOOOdc:oxO000KKXXXNNNKkc'.,;';lxkOkkOOOkkkkkkOkl::okOOOOkkkkOkkOOOkkOkdc;;c;;okOOOxdoc'.............,cdxdlcxOOOkkkkkkxdoooooooooooooool
lllllllccc:::;;:::;..;okOOkkkkkOkkkkkxc;lxkOkOOkkkkkkkkkkkkkkkkkkkxdc:dOOOOOOOOOkkkkkkkkkkkkOkdl:lxOOOOkkkOOOOOkkkkkkkkkkOOkOkxollxOOkkkkkOOOOOkkkkkkkkkkkkkkkkOOOkkOOOOOxc;:oxxxxxxxxxk0KXXOl,.';okOkkkOOOkkkkkkkkxdc;:xOOOOkkkOOkkkOOkOOkxl;;l:;cxkOkdc;,,,;,'',:c:,'',;:cddl:oOOkkkkxxdoooooddxxxxdddddoo
lllllllccc::::::::,.':okOOOkkkOOkkkkkxc;lxkOOOOkkkkkkkkkkkkkkkOkkkkdc:dOOOOOOOOOkkkkkkkkkkkkOkdl:lxOOOOOOOOOOOOOOOOOOOOkkkkkOkxlloxOOOkkkOOOOOOOkkkkOOOOkkkkkkkOOOOOOOOOOxc:oOKK000OkkkkO0XNX0d;,lxOOkkOOOkkOOOkkkkkko,;dOOOOkkOOkkkOOOkkkkkdc:clc;;lol:;,,;ldl,,;:oxdc,',;;,,',lkkkxxddoooooooodddxxxxxdddd
lllllllccc:::::::;,.,cdkOOOOOkkkkkkkkx:;lxkOOOOkkkkkkkkkkkkkkkkkkkkd::dOOOkOOOOkkkkkkkkkkkkkOkdl:cxOOOOOOOOOOOOOOOOOOOOOkkOkOkdlcoxOOOOOOOkkkkOOOOOOOOOOOOkOOOOOOOOOOOOOOxccd0NNNXXXXNXXXXXXNNKkl:cxOkOkkkOOkkkkkkOOOd::oxOOkkkOOkkkOOOOOkkOkdc;clc::::;,..:dxd:,,,:dOxl:,,:;'..cxkxdddoolllollooooodddddddd
lllllllcccc:::::;;'.,lxkkkOOOkkkkkkkkd:;lxkOkkkkkkkkkkkkkkkkkkkkkkkx:;okOOkkOOkkkkkkkkkkkkkkOkdl:cdOOOOOOOOOOOOOOOOOOOOOOOOOOkdlclxOOOOOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOxccd0XNXXXXXXNNNXXXNNXXOoc:dOOOOOOOOkkkkkkOkxo::okOkkkkOkkkkkkOOOkOOko:;:ccc:;,...:dkdc,'';okkOxc,,;:,':oddooollllllllllllllllloooo
cccccccccccc::;;;;'.,lxkkkkkkkkkkkkkkxc;lxkOOkkkkkkkkkkkkkkOOkkkkOOx:;okOOOOOOOOOOOOOOOkkkkkOkdl:cdOOOOOOOOOOOOOOOOOOOOOOOOOOkdlclxOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOkkkkOOxccx0XXXXXNNNNNXXXNNNNXXKxc:lkOOkkOOkkkkkkkkkdc,ckOkOkkkkkkkkkOOOkkOOkdoc,',cl:...cdOko;..,:dOOkxl,;lc,;coooollllllcccclllccccllooo
ccccccclllccc:;;;;,.;okOOOOkkkkkkkkkkxc:lxkkOkkkkkkkkkkkkkkOOkkkkOkx:;okOOOOOOOOOOOOOOOOkkkOOkdl:cxOOOOOOOOOOOOOOOOOOOOOOOOOOkdlclxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxxkO0xclxKXXXXXNNXNNNNNNXXXXXNKk:,cdkOOkkkkkkkkkkkkl,;dkOOOkkkkOOOkkkkkkkkkkOd:':dxl,.':dOOd:'''':dkkdl;:l:,,:loollllllllllllllllllllooo
cccclllllllllc:;;;,.;dkOOOOkkkkkkkkkkxc:lxkkOOkkkkkkkkkkkkkOOOkkkkkxc;lxOOOOkkOOOOOOOOOOkkOOOkdl:lxOOOOOOOOOOOOOOOOOOOOOOOOOOkdlcoxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxddkO0xclkKXXXXNNNXXNNNNXXXXXXXXXOo::okOOkkOOOOOkkOko,;lxOOOOkkkkkkkkkkkkkkkOOx:;lkkl'.'cdOOx:'''..,:c;;:c:,';cloolooooooooooodddoddddddd
ccccclllllllcc:;;;'.,okOOOOkkkkkkkkkkxl:lxkkOOkkkkkkkkkkkkkOOOkkkkOxc;lxOOOOkkOOOOOOOOOOkOOOOkdl:lxOOOOOOOOOOOOOOOOOOOOOOOOOOkdlcoxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxodxO0xclkKXXXXNNNXXXNNXXXXNXXXXNXKd:;ck0OOOOkOOOOOkd:,:dkOkOOkkkkkkkkkkOkkkOOx:,ckkl'.,cdkOkl;,'.',;;:ccc:;;ldddddddxxxdddddxxxxxkkkkkkk
:::::::ccc::::;;,,..'oxkOOOkkkkkkkkxkxl:lxkkOOkkkkkOkkkOOkkOOkkkkOOxc;cxO0OOkkOOOOOOOOOOOOOOOOdl:lxOO0OOOOOOOOOOOOOOOOOOOOOOOkdlcokOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdooxO0xclOXNXXXNNNXXXXXXXXXXXXXXXNNKkl::okOOkkkOOkkkxl;;lkkkOOOOkkOOOkkkkOOOOkd:,lxxc'.,cxkOko:;,',:cll:,,:;:okkkkkkkkkkxdddxxkkkOOOO00OO
;;;;;;;;;;;;;;;,,,..'lxkkkkkkkkkkkkkkxl:ldkkkkOOkkOOOkOOOOkkkkkkkkkxl;cdkOOOOOOOOOOOOOOOOOOOOOxoccdOOOOOOOOOOOOOOOOOOOOOOOOOOOxllokO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxooxO0xcoOXXXXXNNNNXXXXXXXXXXXXXXXNNX0d:;lxkOOOOkkkkkd:,cxOOOOOOkkOOOkkkkkkkkkd:;oxd:'';:oxOko:;,,,'','',;;',ok00OOOOOOkxxdxxxkkkkkOOO000
;;;;;;;;;;;;;;,,,,..'lxkkkkkkkkkkkkkkxoccokOkkkkkkOOOOOOOOkkkkkkkkkko:cok00OOOOOOOOOOOOOOOOOOOkdc:dO0OOOOOOOOOOOOOOOOOOOOOOOOOxllok00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxooxO0xlo0KXXXNNNNNXXXXXXXXXXNXXXXXXXXKOo:cdkOOOOOOOOxc,:dkOOOOOkkkkkkkkkkkkkOx:,lxxc,;:,,;cc:,;;;,,::;,::;',lk00OOOOOOkxxxxxxxxxxxkkkOO0
;;;;;;;;;;;;;;;;,,'.'lxOOkkkkkkkkkkkkkdl:cxOOOOkkkkOOOOOOkkkkOkkkkOko:;lk0000OOOOOOOOOOOOOOOOOkdc:oO0OOOOOOOOOOOOOOOOOOOOOOOOOxllok000OOOOOOOOOOOOOOOOOOOOOOOOOOOOkxooxO0xclOXXXXNNNNXXXXXXXXXXXNXXXXXXXNNX0xc:ldkOOOOOOxl;:oxOOOOOkkkkkkkkkkkkkOx:'cxxc,col::::::ll:,:oxo:;:;'':xkOkkOkkxxxdddddddddxxxxkOO
;;;;;;;;;;;;;;;;,,'.'lxOOkkkkkkkkkkkkkxl;:dOOOOkkkkkkkOOOkkOOOOkkOOkdc,:x0000OOOOOOOOOOOOOOOOOkxc:oOOO0OOOOOOOOOOOOOOOOOOOOOOOxolok000OOOOOOOOOOOOOOOOOOOOOOOOOOOOkdoox00xcl0XXXXXNNNXNNNNXXXXXNNXXXXXXXNXXXKOo::okOOkkkkoc:lxOOOOkOOkkkkkkkkkkkOx:,lkxc,:ododdooool:;:dkdc,,;'.;ldxddddoooooooooooooddddxxk
,,;;;;;;;;,,,,;;,,'.':dOOOkkkkkkkkkkkkko;;okOOOkkkkkkkOOOkOOOOOOkOOOxl,;dOO00000000OOOOOOOOOOOOxc;oO000OOOOOOOOOOOOOOOOOOOOO0Oxolok0000OOOOOOOOOOOOOOOOOOOOOOOOO0Okdook00xclOXXNNXXK00KXNNNNNNNNXXXNNXNNXXXXNX0kl:cxkOkkkdl:cdOOOOOOOOOOOkkkkkkkkx:;okxl;;:cclc::;;,',;okxl;,:;',:lollllcccclllllllllooooodd
,,,,;;;;,,,,,,,,,,,.';okOOOkkkkkkkkkkkko;,lkOOOOOOOOOOOkkkOOOOOOOOOOOo;;okO00000O00OOOOOOOOO00Oxc;oO000OOOOOOOOOOOOOOOOOOO0O0Oxolok00000000OOOOOOOOOOOOOO000OOO000kdodk00xclOXXXX0OxxkOKXXXXXXXXXNXXXXNXXNNXXXXXOdccoxOOkxo;;oOOOOOOOkkOkkkkkkkkkd:;dOOxdllcc::;'.,;;,;oOOd:;::,,;clcccccccccccccccccccccccc
,,,,,;;;,,,,,,,,,;,'.'lkOOOkkkkkkkkkxxxo;,cxOOOOOOOOOOOkkkOOOOOOOOOOOx:;okO0000OOOOOOOOOOOOO00Okc;oO00OOOOOOOOOOOOOOOOO0OO000Oxolok0000000000000000000000000OOO000kdodk00xclOKXXX0OkO0XNNNXXKXXXNX0k0NNNNNNXXXXXXKkoccdkkko,'oOOOOOOOOOOOkkOkkOkkd;;okOOkkkkkkkxc,;cc:;lkOxl:::;,,:cccccccccccc::::::::::::;
,,,,,,,,,,,,,,,,,;,,.'cxkkkkkkkkkkkkkxxd:;:dk0OOOOOOOOOkkOkdoxO0OOOOOkl:ldO00O00OOOOOOOOOO00000kc,lO00OO0000OOO0OO000000000OOOkolok0000000000000000000000000000000kooxO00xclOKXNXXXXXXXNNNXXXXXKKOdlkXXXXNNNXXXXXXX0xl:coxd,'lkkkkkOOkkkkkkOkOOOko,'coxkkkkkkkkkl;;clc;lkOkoc;::,':c::ccllllcccc::::::::::::
'',,,,,,,,,,,,,,,,,,'.:dkkkkkkkkkkkkkkkxl;;lk00OOOOOOOOOO0kl;oO000OOOOdc:oO000O00OOO00OO00O0000Ol;lk000O00000O000000000000kooxkdlok000000000O000000000000000000000kooxO0Kx:lOXXNXXXXXXXKOdolcc:;,'.',:::ldk0XXXNNNNXX0xc;:c,'lkOOOOOOkkkkkkOOOOOxoccolcokkkkkkOko::cl:;lkOkdc,;c,';::::cclllcccccccccccccccc
,,,,,,,,,,,,,,,'''','.,lxOOkkkkkkkkkkkkkd:,ck000OOkxkkOOO0Oo:lk0000OOOxl;lO000000000000000O0000Odclx000000000O00000O000000xccdkdllk0000000000000000000000000000000kooxO00x:cOXNXXXX0kdl;...         .   ...,cdkO0KXNNNXOo:'.'oOOOkOOOOkkOkkOOOOkdldkOd:cdkkkkOOkoc:cl:;lkkkd:',:,';::::::cccccccccccccccccc:
''',,,,,,,,,,''''''''.':dOOOkkkkkkkxxkkkxc,:x0000OkdodkOO0OdlldO000000Oo,:k0000000000000000000K0xlcdO0000000000000OO00000Kkccdkxlcx0000000000000000000000000000000kooxO00x:ckXXKOkl,...   ...',,'.  . ...  .....'cx0XNNNKOo'.ckOOOOOOOOOOOkOOOOkocdOK0koldkkkkOkdc:cl:;cxkkx:.,:;';:::::::ccccccccccc:::::::
'''''''''''''''..'''...,lkOOkkkkkkkxxkkkko;:dk0000OdccdO00Okoclk0000000d;:xO000000000000O00000K0xlclk00000000000000000000KkccdOkl:x000KK000000000000000000000000K0kooxO00x:cOKOdl:,. ... .ckO00kc. ........      ..;d0XNNN0c,cxOOOOOOOOOOOOkOkOxl:d0XX0o:lkkkkOkdl::l:;cdkkx:.'::;;:cccccccccccccccc::::;;;;
''''''''''....'.'''''...;dkOkkkkkkkkkkkkkdl:cdO0000xc:lkO00Od::x0K00000xc:ok000000000000000OOO00ko:ck000000000000000000000klcokkl:dO0KKK000000000000000000000000K0kooxO0Kx:ck0Okxo;'':c,..:xOOdc,...........  ...   .;d0XWXo:lxO0OOOOOOOOOOOOkkxc;dKXNKd:cxOOOkkxl::c:,:dkkx:.,cc:;:clllllllllllllcccccccccc
''''''''''.....''''''...'cxkkkkkkkkkkkkkkxd:;oO00KKOdccdO000x:;d00000K0koclk000000000000000kdxO0Od:cx0K0000000000O00K000KKOoclxkl:dO0KK0000000000000000000000000K0kooxO00x:ckXXKklldOOo,. ..''......................  .:kXKd:lxkkkkOOOOOOOOOkkkxc;dKXNXkllokOOOkxo::c:,:dkOx:.,ll:;:clllllllllllllllllllllll
'''''''''''''''''',''....,okkkkkkkkkkkkkxxx:,ck00KK0kdclx0KKOl:ok000000Oxlcd000000000000000xooxO0x:;x0K0000000K0000KKK00KK0dccxOo:ok0KK0000000000000000000000000K0kooxO0Kx:cOXNK0O0XNKl.   ...',,,....'''.....  .;ll;. .,lo:'cxkdodkOOOOOOOOOkkdc:xXNXX0dllxOOOOxo::l:,:okkx:.'clc;;cllllllllllloooooooooooo
''''''''',,,''',,,,,,'''.'cxkkkkkkkkkkkkxkxl;:ok00000kc:dOKK0xlcoO00KK00Oo:oO00000000000000kocoO0x:,o0K000000KKK000K000KKK0xlcdOocok0K00000KKK0000000000000KKK00K0kooxO0Kx;cOXNNXNXXN0l.  .';;:c:;...',;;;;,'.  .lk0kl,. .;,,lkOocokOOOOOkkOOOxoclkNNXX0klcdOkOkxl::lc,;okko;.'ccc;;cllllllllloooooddddddddd
''''',,,,,,,,,,,,;,,,,,,'';lxkkkkkkkkkkkkkkxl;:d000KKOl:lxKK0Od;ck00KKKK0d:lk0K0000000000K0Oo:lOKk:,lO0000000KK0000K000KKK0xlcdOdclx0K0000KKKKKK00000000000KKK00K0kooxOKKx:cOXNNXNNNNKd'..':cllol;...':clllc;'..,xKXKOo'.'llcokko:okOOOOOOOOOOxcco0NNXXKklcdkkOkxl::lc,;okxc'.,:lc,;clolllllloooooooddoooooo
'''''',,,,,,,,,,,,,,,,,''..;dkOOkkkkkkkkkkkkx:,cxO00K0xc:oOKKKx::x0KK0KKKxccdOKK0000000KKKK0d;:kKOc;lk0K0000K00000KK000KKK0kl:oOxlldOK000KKKKKKKKKKKKKKKK00KKK00KKkolxOKKx:cOXNNXXXNNKk:..,clllol:'.';cooool:'.'l0XXXKx;.;xocdkkocokOOOOOOOOOOo:cxKXNXXKklcdkkkkxl:clc,;odo;,,;clc,,cooooooooooooddddooooooo
''''''''''''''''''''','''..'lxkOkkkkkkkkkkkkxl;;ckKKK0Oo:ck0KKOoclkKK00KKko:lkKK0KKKK0KKKKK0x;:x00dclx0KKKKKKK0000KK000KKKKOo:oOkocoOK00KKKKKKKKKKKKKKKKKK0KK000KKkllx0KKx:l0XNNXXXNXX0l..,coooool:;:loodxxkd;,ckXNNXKx:'lko:okkocokOOOOOOOOOOo;lOXXNNXOdccxOkkkxo:clc,;ll:;;ccccc,,codoooooooooddddddoooddd
....'''''''''''''''''''''..':dkkkkkkkkkkkkkkxdc,;d0KKK0xc:oOXX0klcd0K0KKKOx:;x0KKKKKKKKKKKKKkccoO0kocoOKKKKKKK000KK00KKKKKKOo:lOOo:lOK0KKKKKKKKKKKKKKKKKKKKKK000KKkllx0KKx:l0NNNXXXXXNKd,.':odddddddooddxOKXKkxOXNNNXKOdokOo;oxxlcdkOOOOOOOOOkl:oKXXXNKxccoxOOOkxo::lc,;c;,:llc:cc,;ldxdoooooooodddddddddooo
.......'''''''''..'''....''';lxkkkOOkkkkkkkkkkd:;lk0KKK0xc;o0KK0d:lOKKKK00k:,o0KKKKKKKKKKKKKOdllk00d::xKKKKKKKK0KKKKKKK0KKK0d:lOOo;ckK00KKKKKKKKKKKKKKKKKKKKKKK0KKkllx0K0d:l0NNNXXXXXNX0d;.,cdxkkOOkkkkxxxkO0KXXXNNNNXXKKK0l;okxlcdkOOOOOOOOkxl:dXNNNXOl;cxkOOOkdl;:lc,,,,;ldo:;:c;;oxxdllllooooddddddddolcc
.......''''''''...........''':okkkkkkkkkkxkkkOko:;lkKKKK0o;cx0KKkllxOKKKKK0o:lk0KKKKK0KKKKKK0xlcd0Kx:;d0KKKKKKKKKKKKK0KKKKK0d:lOOd;:kKKKKK00KKKKKKKKKKKKKKKKKKKKKKkllk0K0d:l0NNNXXXXNNNXKkc;;lxO00000K0kdllokKNXXXXNNNXXXXOl:dkdlcdOOOOOOkkOkdllkXNNXOoccdkkkkOxl;,:lc,'.,cool;,:c,;lddocccclllooooodddolc::
'.....'''''''''''............,cxOkkkkkkkkxkkkkkxl,;oO0KKKOo:ckKX0xlcd0KKKXKklcoOKKKK00KKKKKK0ko:o0Kkc:dOKKKKKKKKKKKKK0KKKKK0xcoOOx::xKKKK000KKKKKKKKKKKKKKKKKKKKKKkclk0K0d:l0NNNXXXNNNXXNXKkdoodk0KXKKOxddxOKXNXXXXXNXXXXXOl:dxoclxO00OOOkkOxlld0NNXOo:lxOOkkkxl;.';lc,..;lllc;,cc,,clolc:::::cccccllllcc:::
'''''',,,,,''''''........'....,lxkkkkxkkkxxkkkkkd:,;oOKKKKkc;o0KKOc;o000KKK0d::kKK0KK0KKKKKKKOo:lOKOl:lkKKKKKKKKKKKKK0KKKKK0xllxOkccx0KKKKKKKKKKKKKKKKKKKKK00KKKKKx:ck0K0xco0XNXXXXNNNNXXXXXX0OkkOKXK0OO0KXXXXXXXXXNXXXXXKOlcxkoloxO0OOOOOO0x:cxKXKxlclxkkOOkko;,',:ol;',:clcc;,:c,,:llc:::;;;::::::::::::::
''''',,;;;,,,'''''.......'.'...,lxkkkkkkkkxxkkkkxd:,;oOKKK0d:cxOK0o:lk0KKKKKk:;d0KKKKKKKKKKKK0d;ckK0dccd0KKKKKKKKKKKK00KKKK0koldOklcx0KKKKKKKKKKKKKKKKKKKKK00KKKKKx;ck0K0xco0XXXXXNNNNNXXXXXXXNXOox0kdk0KXXXXXXXXXXNNXKXX0kllkklldk00OOOO00Oo,:kX0dc:oxkkkOkxo:,;:;:ol;,;:clc:,,cc,,:ccc:::;;;;;;;;;;::::ccc
''''',,;;;;,,'''''......'''.....,lxkkkkkkkxxkkkkkxo:',d0KKKOo:cxKKOdclkKKKKXOo:cx0KKKKK0KKKKKKx::d00Oo;l0KKKKKKKKKKKKK0KKKKKOdllkOoldO0KKKKKKKKKKKKKKKKKKKK00KKKKKd,:k0K0xld0XXXXNNNNNXXXXXXXXXX0xk0Okk0KKXXXXXKKKXXXXXXKOdodkxllxO0OOOOOOOkl;cOOd::okOOOOkko:;clc;:ll;,;:clc:,,:c,,:cllcc:::::::::::::cclll
.''''',,,,,,,,'''''......''......,lxkkkkkkkkkkkkkxxd;'ckKKK0kc:oOKKOc;oOKKKK0ko:lOKKKKKKK0KKKKkl:lkKKd;cOKKKK0KKKKKKKK0KK0KK0xl:dOxlox0KKKKKKKKKKKKKKKKKKKKKKKKKKKd,:k0K0xldKXXXNNXXXXXXXNXXXXXXXKKKKKKKXXXKKKXKKKKXXXXXKkooxkd:cxO0OOOOOOOxocoxocldkOOOkkkoc;cddl;:lc;,;:cllc,,:c;,:loollcccccccccccllloooo
.....'',,,,,,,'''''...'''''...'...,lxkkkkkkkkkkkxxkkoc;ckKKK0xl:lOK0d:cdOKKKK0x:cx0KKKKKKKKKK0Odc:dKKx:cx0KK0KKKKKKKKK0KKKKK0kl;oOkold0KKKKKKKKKKKKKKKKKKKKKK00KK0d,ckKKOxoxKNXXNNXXXXXXXXXXXXKKKXXXXXXKKKKKKKKKKKXXXXXXKxcokko;ck000OOOO0OdoddlcldkOOkkkxo;,cdkdc;:lc;,;clllc;,:c;,coddolllllccc:ccccllllll
......'',,,,,,'''''...........''...,lxkkkkkkkkkxxxxkkd;,lOKKKKx:;d0KOo;;xKKKKKkl:okKXKKKK000K00kc;oKXklcoOKKKKKKKKKKKKKKKKKKKOl;oOOocoOKKKKKK0KKKKKKKKKKKKKKK000K0d,cOK0kdokKNXXXXXXXXXXXXXXXXXKXXXXXXXKKKKKKKKKKKKKKKXX0d:dOkl,ck00000000OkdolcoxkkkkOOxl,,:okxo:;clc;;:clllc,':c;;:loollccc::::::::::::c::
......'',,,,'''''...................,ldkkOOkkkxdoloxkxl:,lOKKKOo::d0Kk:;ok0KXK0xc;oOKKKKK00000K0o:oOKOxc:d0KKXKKKKKKKKKKKKKKK0d:oOOo;cOKKKKKKKKKKKKKKKKKKKKKK000K0o,cOKOdldOXNXXXXXXXNXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKOl;okxc,lO0000KKKK0Oo::oxkkkkOkxl;,cdxkxc,,:lc;:cloolc,':c;,;clc:::;;;;;;;;;;;:::::;
......'''''''.....................''',:dkOkkkkxdoccldxko;'cx0K00o;ckK0xl:o0XXXKOl':x0KKKKKK00KKKxllx0Kkc;o0KKKK00KKKKKKKKKKKK0xloxOx::x0KKKKKKKKKKKKKKKKKKKKKKKKK0o,:OKOdok0XXXXXXXXXNXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKK0OocdOkolx0KKKKXXK0x:,;lxkkkkkkd:';ldxkxo;.':cc::looolc,':c;,;:cc:::;;;::::;;;;;::::;
......''''''...................'',,;,'';oxkkkkkkdc::coxkd;.;d0KKkoccx00d:cdOKXXKd::lkKXKKKKKKKKKklcokK0o:lk0KKKKKKKKKKKKKKKKK0kdloOklcdOKKKKKKKKKKKKKKKKKKKKKKKKK0dco0XKkk0XNXXXXNXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKK000KK000KXXXNNX0o,.,lxkOkxdoc;''cxkkxo;..,ccc:coddol:'.:c;,,;:::::;;::c:::;;;::::;;
...'',,;;;,,'''''''..'''''''',;::cc::;'',cdkkkkkxoc;;coxxo;',o0KKOl;ck0Odc:d0XKKOdc:xKXKKKKKKKKKOdlokKKkoox0KKKKKKKKKKKKKKKKKK0kookOdlokKKXKKKKKKKKKKKKKKKKKKKXXXXK0KXXXXXXNNXXXXNXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKXXXKKXXXXXXXXXXXKOd:,',:oxOOkdc;'.,cdkxdc;'..;lc:;lxkkxo:'.:c;'',::::::::cccc::::::::;;
::::cclllcc:;,,,,,,,,,;;;;::clloodoc::;;'';lxOOkxdl:;;:ldxdc,;lOKKkc;cx0Ol;cx0KKK0xox0KKKKKKKKKKK0OO0KK0OO0KKKXXXXXXXXXXXXKXXXXKK0KX0O0KXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXNNNNXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKXXXKKXX0xodOKK0kc,..',:ldxkxoc,'';lxxdl:,,,..;cc;;lxkOkdc'.;c;'',:::::::ccccc::::::;;,,
ddddddxddolc:;;;;;:::cccllloddxxxdoccclol:;,:dkkxxoc:;;:ldxdl;,cx0Kkc,:dOkocokKKKK0O00KKKKKKKKKXXXXXKXXXXXNXXXXXXXXXXXXXXXXXXXXXXXNNXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKXXXXXXXXKOl'.';cc:,''..',:oddol:,',coddl:,,,,,'.;c:;;:odxxdc'.;c;'';::::::::c:::::::;;;,,,
kkkkkkxddoc:::::::::clooddddxxddolccccloddo:',cdxkxo:;;;:cldxoc;;ok0kl:lO0Oxx0KKKKKKKKXXKKKKXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXXXXXXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKXXXXXXXXXXXXNNX0l,..',,,,,,'..,coool:;,',cddl;,',,,,'.';c:;;:cclll:'.;c;',;:c:::::::::::::;;;,,,,
xxkkxddlcc:;;:::;;::cloddddddoolc:;;;;;:cccc;'';lxkxl:;;;;::ldoc,':dOOxxOOOO0KXXXXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0kkKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKXXXXXXXXXXXXNNKx;..,;;;;;,...,:loc:;'.';clc;,,,,,,,,,'':c;,,;:::::;..;c,',;cccc::;;;;;;;::::;;;;;
ddooollc:::;;;;;;;;;:ccclllllllc:;,,,'',,,,;;;,'';lddo:,,,;,,;cooc:lxOOOOxoox0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOoo0NNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXKkc''';:;;,'...,;:c:;,..',;:;,,,,;;;,,;;,,cc,,;;:;;;;,..;:,',:ccccc:::;;;:ccllllllll
:::::::::;;;;,,,,,,,,,,;;;;;;;;;,,''''''''',,;;,'.';llc;;;;;'',coxxxkkkkkxl:cxKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKOOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkc..,;;;;,'...',;;;;,'.',,,,,;;::;;::::::;c:,,clcc:;;,..;:,';clllllllccclodxkkkkkkkk
.''',,;;;;,,,''''''''''''''''''''''''''''''',,;;,;,'',;;;,;;;,'';oxkOOOOOOxlcokKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKx;'',;;,,,...',;;:;,'...'.',::::ccc::cccc::c:',coolc::;..;:,':cooooolllllodkO00000000
...'',,,,,,,,''''''''''''''''''''''''',''''',,;;;;:;;,'..',,;;,'';cdkOOkOOOxl:cxKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOo;'',;;,,'...,;;;;,'....''',;:ccccc::cccc:::c:',cllllcc;'.;:,,:looooollllodxxkOOOO0000
'',,,,''''',,,,''',,,,;;,,,,''''''',,,,,,,,,,,;;;::::;;'...',,;;,'':oxkkkOOkdl:lkKNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkc'.',;;;,'...,;;;,'.....',,;;::::::::::c::;;:c:'':ccllcc:'';:'';clollllllooodddxxkkkOOO
::;;,,'''',,;;;,,,;;;::::;;,,''''',,,,,,,,,,,;:cccccc::;,'....'',,'',cdkkkkkkxoclx0XXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXKOd;...,;;,,'..',,,,,'...'''',;;;;;;;;:::::::;;;:c;',:cccccc:,';:'';cllcccllllooollooddxxxx
cc::;;;,,;;;::::;::::;;;;;;,,,,,,,;;;;;;;;;;;:cloooolc::;;;;;'...','..,:odxkkkxoc:d0XNNXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXXNNNXXXXXXXKkc'...,;;,'...',,,'....',,,',,;;;::;;;;;;;;;;'';c:,,;clccccc:,,;;,,;ccccccllllloolllooooddd
:::::;;;::::::cccccc:;,,,'',,,,,,;;;;;;;;;;;:cloddoolc:::;;;;,,''.......';oxkkkxl::d0XXXNNNNXXXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXXXXNNXXXNKkl;'...';;,..'',,,'....',;;;,,;:::cllc:;,,,,,,,'';c;,;cllcccccc:;::,,:ccccccclllllllllloooooo
;;;;;;;;;;:;:::cllllcc:;,'''''',,,,,,,,,,,,,;:cllllc::;;;;;,,,,,,''.......',coxkkdccoOXXXXXXXNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXXNNXXXXXXXXKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNX0xl;'.','.','...',,'...',:ccc:;;::clodddlc:;;,,,,,''::,';:cccccc:::::;,;:cccccccccllllooolllllll
''',,,,,,,,,,,,;::cccc:;,,,,,,,,,,,;;,,,,''',;;;:;;;,,,,,,,;,,,,,,,,,,,,,'...';cdxxollkKXNXXXNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXXXXK0OOOkkkkxxxxxxxxxxkO0KXXXXXXXXNNXXXXXXXXXXXXXXXXXXXXXNNXXXXXXXXKOdc,''',,'.'....','....';cloolcc::clodxkkkdllcc::;,,.':c,..',,',:cc::::;;;ccc:::::cclllloolllllooo
'''''''''''''',,,,,,,,,,,''''',,,,;;;,,,'''''',,,,,,,,,,'',,,'''',,;;:::::;,....':oxdlcok0XNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0o:;;::::ccccccccccc:cokKXXXXXXXXXXXXXXXXXXXXXXXNNXXXNNNXXXXNNX0kl,.'',,;;'.....'''....';clloollc:clodxxkOOkxddolc:;,'.':c::dkOkxoc::::::;::cc:;;;;::clllllcclllodxx
'''''''''''''''''''''''',,,,'''',,,;;,,''.....''',,,,,''''','''''''',;;:::c:;,'...';:clcclxKXXXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkc;:cclllloooooooollc:ckXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNX0xc'...,;;;;,.....''....,;:cllllllcccloodxkkOkxddol:;;;;;,,;:cd0NNNNKkl;''''';:c::;;;;:cccclllccclldxkk
''''...''''''''''''''';odxkkxdolc;,,,,,''....''''''',''''',,'.......''',,,;,'''.......,::;;:dkKXNNXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkc;codddxxxxxxxxxxxoccoOXXXXNNXXXXXXXXXNXXXXXXXXXXXXXXXXXXKkl;.....,;;;;,'.........,:ccccccccccccllooddxxxdol::::lxkOkl;;:okXNX0OOkdc,,,;:oxkkOOOOkkdl::cllccccldxxk
'''.....''',,,',,,,,',o0XXXXXXXXKOdl:;,''';clooolc:;;,'''''''..'.....''''.................'''':ok0XNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0o;:ldxxxxxxxxkkxdlcldOKXXXXNNNXXXXXNNXXXXXXXXXNXXXXXNNXOo:,''''...';;;,,'.....',;:ccc:::::::::cc:cccllolc::ccoxOKXXXOo;;lk00koolldkOO00KKXNNNNNNXNXK0xoc:;:cccloxxx
........''''',;:cc:,;lOXNNNNNXXXNNXKOxl;,:d0KXNNNXKOkdl:;,''''''.....'''.....''',,,'''..........':ok0XXXXXXXXXXXXXXXXNXXXXXXXNNXXXXXXXXXX0dlcloddxxxdolllcldOXXXXXXNNNXXXXXXXXXXXXXXXXXNNNXXX0xl;''',,,'...',;;;;;,'',;;::::::;;;::::::::::::::;;:ldk0KXNNNNXKkoccoddxxkO0XXXXXNNNNNNNXXXXXNNXKOl;;:cllooooo
........''''',:clo:;ckKNNNNNNNXXXXXNNXKkdlldOKNNNNXXXXK0kdc;'......''.'....',;:::;;,''...'',,,'...',:oxO0XXNXXXXXXXXXXXXXXXNNNNXXXXXNNNXXNXKOkkOO00OkxxxxO0XXXXXXXNNNXXXXXXXXXXXXXNXXXNNXK0xl;'......'''''',::ccc::;;;;;;;;;;;;;;;;::::::::;;:coxOKXXXNNNNNX0kolloxO0KXXNNNNXXNXXNNNNNNXXXXNNNN0o;:cllllccc:
..'''''''....',;::;;lOXXXXXNNNNNNNXXXXXXKOddkKXXNXXXXXNNNXKOd:'......''...'',;:::;,'.......',,'..''''..':dOXXNNNNNNXXXNNNNNXXXXXXXXNXNNNXXXXXXXXXXXXXXXXXXXXXXXXNNNXXXXXNNXXXXNXXXXXNNKOxc,......',,,;;:ccccllllc::;,,,,;;;;;;;;;;;;;::;;,,:lx0KXXNNNXXNX0dlccoxOKXNNXXXNNNXXXNNXXXXXNNNNNNXXXXOl;:cllcc:;;,
''',,,''''........',o0XNNNNNNXXNNNXXXNNNNXKKKKXXNNNXXXNXXXNNX0kdc,'...'''.'''','''................',,.....,coxO0XXXXNNNNNXXXXXXXXXXXXXXNNNNNXXXXXXXXXXXXXXXXXNNNXXXXXXNNNNXXXXXXXXXKOdc,...'',,,;:cclcccllcclllcc:;,''''',,;;;;;;;;;;;,,;cdO0KXXXNNNNNX0dc:ldOKXNNNNXXXXNNNNNNNNNNNNNNNNNNXXXXXOc,;clcc:;,,'
',,,,,,,,''........,o0XNNNNXXXNNNNNXXXNNNNXXXXXXXXNNNNNXXXXXXNNXKkl;'.....''.......................',''......',:oxk0XXNNNXXXXXXXXXXNNXXXXXXXXXXNNNNXXXXXXXXXXXXXXXXXXXXXXXXNNNXK0kdl:::;',;::cccclccccc:ccccclccc:,'......',,;;;,,,,',:okKXXXXXXXXNNNNX0kkOKXNNNNNNNXXXNNNNNNNNXNNNNNNNNNNXXNXKk:,;:::;;,,''
,,,,;;;;,,'''......,o0NNNNXXXNNNNNNNXXNNXXNNNNNNXXXNNNNNNNNNNNNNNNKOdc;'..........',,,,'''''.......'''''''..'''''',:ldk0KXXXXXXXXXNNXXXNXXXKXXNNNNNNNXXXXXXXXXXNNXXXXXXXXXXXK0xoc;:lx0Kkc;;:ccccccc::;;::clloooolc;,'''''...',,,''';ldOKXNNNNNNXXXNNNXXXXXXNNXXNNXNXXXXNNNNNNNNNNNNNNNNNNNNNNXOo;,,,,,,,''''
',,,,,,,,,'''''''..,dKNNNXXXNNNNNNNNNNNXXXNNNNNNNXXNNXNNNNNNNNNNNNNNXK0ko:'.....'';:::::;,,,,,,'''''''''.';lkOOxocc:;;::coxk0KXXXNNXXXXXXXXXXNNXXNNNXXXXXXXXXXXXNNXXXNXXX0Oxo:,.,d0XXNN0o:,;cc::::::;;:cloddddddol:,,,,''.',codl::dOKXXNNNNNNXXNNNNXXXXXXNNNNNXXXXXXXXXXXXXNNNNNNNNNNNNNXXNXX0d:,''',,''''''
''''''''''''''''...,dKNNNXXXNNNNNNNNNNXXXXXXXXNNNXXNXXNNNNNNNNNNNXNNNXXXKOo:,...'',;;;::;,''','''',''....;o0XNNNKKXX0Ox:'',:lodkOKXNNNNXXXNNNNXXNNNXXXXXXXXXXXXXNNNK00kdolc:cc:,c0NNXNX0x:'';::::::;;;coxxxxxxxxxo:,'..',:okKX0xdx0XXXXXXNNNNNXXNXXXNNXXXXNXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNXNXKOl,,,,'''''''''
..........''''''...,dKNNNNNNNNNNNNNNNNNNXNNXXXXNNXXXXNNNNNNNNNNNNNNNNNXXXXX0xl,......',,,,,,,,,,;;;,,'...l0NNNXXKKXXKX0l;:odlcccccloxO0KKXNNXXXNXXXNNXKKKXXXKKK0Oxoccccccccllc;':kXNXNNKkc'';;;;;;;;,;codooollcllc;'..;lx0KXXX0ddOKXXXXXXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNXNN0d:,;;;,,,,',,;;
...........'''''...,dKNNNNNXNNNNNNNNNNNXXXXXXXXXXXXXXXXNNNNNNNNNNNNNNNXNXXNNXKd,,lol;'..';:c:::cccll:,'':kXNNXOdoodkkxo;.,ldkkxdolcc::;;cokO00KKXXKkoooollool:;;;::cldolccloooc::lkKNNNKkc'';;;;;,,,,,,,;;,,,''''...,lkKNXXXXXkcl0XNNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNXXNXx:;;:::;,,,,,;;;
...................,dKNNNNNXXNNNXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNXNNOllOXKOo;'.',:ccloddddl:,:xKNX0xoldk0K0OOxl:;:ldkOOkkkxolc::ccccloolccoxkxc'.'::,.,cxkkdlcokO0KK00kold0XNKd:'',;;,,,''..............'ckKXXXXXXX0d:o0XNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkl,;cc:::;;;;;;;;
...................,oKNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXNNNNNXXNNNNNNXXNNOldKXXXX0xl,..';cldxddoc;ckXKkoox0XNNNXXNXK0xc;;lxkkOOkkkxxxddol:;,:d0XXK0l..;kKkl;:odocdOKXNXXXXNX0o:o0Xk:..'''''''..............':x0XXXXXNNN0xllkXNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXNNXXXXXXXNXOl;;:cc::::;;;;;;;
...................,dKNNNNNNNXNXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNXXXNXXNNNNXNN0ooOXNXXXNXOo,..',:::::;,:okkllkXNNNXNNXXXNNX0x:;:oxkxdoollcc:,,;lx0XNXkdl'  ,kXX0d:,:ox0XNNNNXXXXXXOlld0k;......................:d0XNXXXXXNNNOlcxKNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXNNXXXXXXXXNXXKx;,;::::;:;;;;;;;;
...................,dKNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXNNXkod0NNNXXNNN0l'''',;;;;;,',;;:o0NNXXXXNNNNXNNNXOl;:olc:clc;..';lkKXXNKx:,....,oOXXKx:':kKNNNNNNXXXXXKkooOXkl;...................:kXXXNNNXXXXXKklo0NNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNXXXXXXNNXKxc,,;;;;;,,;;,,,,,,
...................'oKNNNNNNNXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNX0dldOXNNNNXXXX0o:lodk0000kdol::oOXNNNNXXXNNXXNNXXX0d:,;okOdc;:ok0KXNX0xl;:lokOxc'cOXXXOo;:o0XNNNXXXNNNX0xd0NNKOxolc:;::c:::;,'.',;o0NNXXXXXXNNKxox0XNNXXNNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNXNNNNXKk:'',,,,,,,,,,,,''''
.....'''......''....c0NNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNKkooOXXXXNNXXXKklcldkKXNNNNNNXKKXXXXXNNXXNNXXXXXXXXN0c,coo:,;oOXXXXXKxc;cdOKXNXOc'.;xKXXKd;,:okKXNXXXXNNXKKXNNNXXXXKXXXKXXXX0koloooxKNNXXXXXNNX0lckXNNNXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXNNNNNNNNXOl'.'''''',,,''''''''
.....'''.....'','...:kXXNNXNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXOxxOXNXXXNNXXX0koclxOKNNNXXNNNXXNNNXXXNNNNXXXXXXXXNNKd;,'.;oOXXXXX0xl:lxOKNNNXOc:lc;cx0XXXOl,,:okKXNXXNNXXXXNXNNNNNNNNNXXNNX0xxkxdxOKNNNNNXXXX0kod0NNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXNNXXXXXKo,.....',;;;;,''.....
.....'''......,,'...,o0XNNXXNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNKkdx0XNNXNNNNNX0xolld0XXNNXXXXXXXXNNNXXNNNXXXXXXXXNXOo;.'cx0XXNXKOoccdOKNNNXKOo;;o0Xkc;d0XNXOdc;::ld0XNXXXXXNNXXNNNXXNNNXXXXXkldOxlxKXXXXNNNXNXxco0NNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXNNNXXNX0d;....'',;:cc::,,'....
..............''.....:xXNNXXNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXOddkKNNNXXXNNXOddoldOXXXXXNXXXNNXXXNNNNNNNNNNXXXKkl,.':d0XNNXKOoccd0XXXNNKxo:..;dKNXkc;ckXXX0ko:;;;cd0XNNNNNNNNNNNXNNNXXXXXKkldOdlONNNXXXNXXNXxlldOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXNNXXNX0o,....',,;::::::;;;,...
................... .'oKNNXNXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXOxdkKNNXXXXNNXOoddld0XNNNNNNNNNNXXXXXXNNNNXXXXOdlc:,,oOKXNNKko:cx0XXNNX0xlclodoclx0XN0oclkKNXXOo:;:c::lkXNNNXNNNNNNNNNXXNNXOxodxdd0WNXXXXXXXXXX0kold0NNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNXXNNXXNNXXXXXXOo,....,;;:::;,,;;::::,''
.................... .cOXNNNNXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNKkod0NNNNNXXNXkloold0XNNXXXNXXXXXXXXXNNNNNXKOo::llclxKXXXX0d::d0XNXNNKkl:lkKKXKOdcoOXX0d:lk0XNX0o,:odo;;oOXNNNNXNNNXXNNXNNKxoddodkKNXXXXXXXXXXXXXkccONNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNXXNNXXXXXkc.....';:c::;,''',;:cc:;,
......................'l0NNNXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXkll0NNNNXXXNXklooloOXXNXXXXXXXXXXXXXXNNNX0d:;loc:lkKXNXK0ocoOKXXNXKOdookKKKKKKXOdloOXXKkl:d0NNX0d;,o0Oo;:d0NNNXXNNXXXXXXN0olkd:lOXNXXXNNNXXXXXNNOccONNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNXXXXXXXNNKx:......,;:c::;;,,,,;:cc::;
.......................,dKXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOccOXNNXXNNNXklodloOXXNXXXXXXXXXXXXXXXNXOo:cxxl:lOKXXXX0dok0XNXXX0xodk00xollolldOdld0XNXx::d0NNXKo,:dKKkc:dKNNXXXNNNXNNNXOooOd;l0NNNXNNNNNNNXXXXOll0NXXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNXXXNNNXX0xc,......',;;;::;;;,,,;;:::;;
.....'.......'''........:kKNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXX0c:kKXXXXXNNXklodloOKXXXXXXXXXXXXXXXNNXOlcoxd:;oOKXXXK0xlxKXNNNXkold00dc:lddd:..ldoxOXNXKkc:dKNNNKx::xKKkl:o0NNXXNNNNNNNKxodkdlxKNNNNNNNNNNNNNKkolxKNXXXXNNNXXXXXXXXXXXXXXXXXXXXNNXXNNNXXXKKK0Oxoc;'....'''',;;;,;;;;;,,,,;;;;,,
...'''..................'lOXNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXKdldOXXXXXNNXkloolok0XNXXXXXXXXXXXXXNXOo:oko;:d0XXXXXkccx0XXXXX0o:okxlclkKNKxlc;,:coxKXXNKdclxXNXXKd:cxKXk;,dKNNNNXXNXXKxldxdox0XNNNXNNXXXNXXN0o:d0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNXKOxlc;,''....',,;;;;;;;,,,;;;;;;;;;;;;;;;
'''''''..................,lOXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXNXKOdldKNNXXNNNkoooodx0XNXXXXXXXXXXXXXKkc;okxllkKXXXNKdccd0XXXXX0dloooloOKNNX0ookOo:;;l0NNNX0o,;kXXXX0o,;kK0d::oKNNNNXXXX0l:dxloOXNNXXXXXXXXXXXXOcckXXXXXXXNNNXXXXXXXXXXXXXXXXXXXXXXXNNXkl,..  .....',,;:cccc::;;;;;,,,,,,;;;;;:::
''''''....................'lOXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXNXXKkloKNNNNNNNOolodddOXNNXXXXXXXXXXXKd::o0K00KXXXNN0d::xKXXXXXKk:;:cokKXNXOdold0X0d;.,dKXNNXk:;d0XXXXOl:cxKKd,;xKNNNXXXXOc;dxlo0XXNXXXXXXXXXNX0dld0NNNXXXXNNNXXXXXXXXXXXXXXXXXXXXXXXXKx:.   ........',:ccccc:::;;,,,,,,,,,;;;;;;;
...........................':x0XXXXXXXXNXXKKXXNNNXXXXXXXXXXXXXXXXXXXXXXXNNXXXKkodKNNNNXNN0dlldddOXNNXXNNXXXNXXOo::d0XXXXXNNXX0o:lkKNNNXXX0o'.cx0KXXXk:..'o0NX0o'.cOXXNXKkold0XNXKOc';kK0o:;oKNXXNN0xloxdlxKXXNXXXXXNXXXXKdcd0XNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXNNKx;. ...........';:cllccc::;;,,,,,,,;;;,,,,,,
.............................'cx0KXNNNXXXNXXNNNXNXXXXXXXXXXXXXXXXXXXXXXXNNNNKxoxOXNNNXXXNKxllddlxXNNNXNNNNNXK0o:lOKXXNXXXXXXkl:okXXXXXXXKd::o0XXNXOo,.  .:ONNXOc';dKXXXNKx::xKXXXKx;,cOX0l':kXNNNXkldkxoxOKXXNNNXXXXXXX0dclOXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXNNNX0c.  ........'',;:ccllcc:::;;,,,,,,,;,,,,''''
...............................'coxxkO0KXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXNXXNNNOlckXNNNNXXXNXOlcxd;oKNNXXXXNNNXkc:oOXNXXXXXNXKOl:o0XXXXXXX0o:ckKNNNXk:......,d0XNXkl:l0NXXNXOl:lkXNXXKx:,o0XOoclkXNNKd:xOdoOXXNNNNXXNNNNXKd:lkKXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXNXO;  ........',,;::ccccc::;;;,,,,,,,,,,,''''..
..................................',,,;cdOKXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXNNOcckXNNNNXXXNXOlcxd,cOXNXKXXNNXOl;cOXXNNXXXNNXKOkk0XNXKXXKkl:d0XNNX0d,..,lddl:cd0NXKOxkKNXXXXKOo:dKNNXXKd::o0N0l,l0X0xoodxoxKNXXNXXXXNNNXOocokXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXNKo'..  ....''',,;;;;;;;;,,,,''''''''''''.....
..................................''....;oOKKXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXOcckXXXXNXXXNN0ocxd;:xKNNXXXXNOc:oOKXXXXXXNNNXXXXNXXXXXX0d:ckKNNNXx:.  .,dO0Kd:ckKXXXXXXXXXXXXKkodOKXXXX0d,,xXKklcoOkclxold0KXNXXXXXXNNN0o',kXNNXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXXXKOdc;'...'''',,,,,,,,,,''.........''''......
*/